#secret: component sur Mastrer Nodes, specifier les credentials
apiVersion: v1
kind: Secret
metadata:
  name: myMongo-secret
type: Opaque
data:
  #encoded; base64
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==